name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: \${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: frontend
      run: npm ci

    - name: Lint & build frontend
      working-directory: frontend
      run: |
        npm run lint
        npm run build

    - name: Run CV unit tests
      working-directory: cv
      run: |
        pip install -r requirements.txt
        pytest --maxfail=1 --disable-warnings -q
