name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Smoke-test frontend
      working-directory: frontend
      run: echo "Frontend OK"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install CV dependencies
      working-directory: cv
      run: pip install -r requirements.txt

    - name: Smoke-test CV module
      working-directory: cv
      run: pytest --maxfail=1 --disable-warnings -q
